export const GET_OFFERS_REQUEST = 'GET_OFFERS_REQUEST';
export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS';
export const GET_OFFERS_FAIL = 'GET_OFFERS_FAIL';
export const REMOVE_OFFER = 'REMOVE_OFFER';

export const GET_LISTINGS_REQUEST = 'GET_LISTINGS_REQUEST';
export const GET_LISTINGS_SUCCESS = 'GET_LISTINGS_SUCCESS';
export const GET_LISTINGS_FAIL = 'GET_LISTINGS_FAIL';
export const REMOVE_LISTING = 'REMOVE_LISTING';

export const GET_BIDS_REQUEST = 'GET_BIDS_REQUEST';
export const GET_BIDS_SUCCESS = 'GET_BIDS_SUCCESS';
export const GET_BIDS_FAIL = 'GET_BIDS_FAIL';
export const REMOVE_BID = 'REMOVE_BID';

export const GET_AUCTIONS_REQUEST = 'GET_AUCTIONS_REQUEST';
export const GET_AUCTIONS_SUCCESS = 'GET_AUCTIONS_SUCCESS';
export const GET_AUCTIONS_FAIL = 'GET_AUCTIONS_FAIL';
export const REMOVE_AUCTION = 'REMOVE_AUCTION';

export const LOAD_MORE_CONTRACTS_REQUEST = 'LOAD_MORE_CONTRACTS_REQUEST';
export const LOAD_MORE_CONTRACTS_SUCCESS = 'LOAD_MORE_CONTRACTS_SUCCESS';
export const LOAD_MORE_CONTRACTS_FAIL = 'LOAD_MORE_CONTRACTS_FAIL';
