export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const LOAD_MORE_USERS_REQUEST = 'LOAD_MORE_USERS_REQUEST';
export const LOAD_MORE_USERS_SUCCESS = 'LOAD_MORE_USERS_SUCCESS';
export const LOAD_MORE_USERS_FAIL = 'LOAD_MORE_USERS_FAIL';

export const GET_MARKETPLACE_ASSETS_REQUEST = 'GET_MARKETPLACE_ASSETS_REQUEST';
export const GET_MARKETPLACE_ASSETS_SUCCESS = 'GET_MARKETPLACE_ASSETS_SUCCESS';
export const GET_MARKETPLACE_ASSETS_FAIL = 'GET_MARKETPLACE_ASSETS_FAIL';

export const GET_MARKETPLACE_ASSETS_BY_TAG_REQUEST = 'GET_MARKETPLACE_ASSETS_BY_TAG_REQUEST';
export const GET_MARKETPLACE_ASSETS_BY_TAG_SUCCESS = 'GET_MARKETPLACE_ASSETS_BY_TAG_SUCCESS';
export const GET_MARKETPLACE_ASSETS_BY_TAG_FAIL = 'GET_MARKETPLACE_ASSETS_BY_TAG_FAIL';

export const LOAD_MORE_MARKETPLACE_ASSETS_REQUEST = 'LOAD_MORE_MARKETPLACE_ASSETS_REQUEST';
export const LOAD_MORE_MARKETPLACE_ASSETS_SUCCESS = 'LOAD_MORE_MARKETPLACE_ASSETS_SUCCESS';
export const LOAD_MORE_MARKETPLACE_ASSETS_FAIL = 'LOAD_MORE_MARKETPLACE_ASSETS_FAIL';

export const UPVOTING_ASSET_REQUEST = 'UPVOTING_ASSET_REQUEST';
export const UPVOTING_ASSET_SUCCESS = 'UPVOTING_ASSET_SUCCESS';
export const UPVOTING_ASSET_FAIL = 'UPVOTING_ASSET_FAIL';

export const UNUPVOTING_ASSET_REQUEST = 'UNUPVOTING_ASSET_REQUEST';
export const UNUPVOTING_ASSET_SUCCESS = 'UNUPVOTING_ASSET_SUCCESS';
export const UNUPVOTING_ASSET_FAIL = 'UNUPVOTING_ASSET_FAIL';

export const TO_FAVORITES_REQUEST = 'TO_FAVORITES_REQUEST';
export const TO_FAVORITES_SUCCESS = 'TO_FAVORITES_SUCCESS';
export const TO_FAVORITES_FAIL = 'TO_FAVORITES_FAIL';

export const REMOVE_FROM_FAVORITES_REQUEST = 'REMOVE_FROM_FAVORITES_REQUEST';
export const REMOVE_FROM_FAVORITES_SUCCESS = 'REMOVE_FROM_FAVORITES_SUCCESS';
export const REMOVE_FROM_FAVORITES_FAIL = 'REMOVE_FROM_FAVORITES_FAIL';

export const GET_ASSETS_TAGS_REQUEST = 'GET_ASSETS_TAGS_REQUEST';
export const GET_ASSETS_TAGS_SUCCESS = 'GET_ASSETS_TAGS_SUCCESS';
export const GET_ASSETS_TAGS_FAIL = 'GET_ASSETS_TAGS_FAIL';

export const GET_ASSETS_STATIC_TAGS_REQUEST = 'GET_ASSETS_STATIC_TAGS_REQUEST';
export const GET_ASSETS_STATIC_TAGS_SUCCESS = 'GET_ASSETS_STATIC_TAGS_SUCCESS';
export const GET_ASSETS_STATIC_TAGS_FAIL = 'GET_ASSETS_STATIC_TAGS_FAIL';

export const ADD_ASSETS_TAGS_REQUEST = 'ADD_ASSETS_TAGS_REQUEST';
export const ADD_ASSETS_TAGS_SUCCESS = 'ADD_ASSETS_TAGS_SUCCESS';
export const ADD_ASSETS_TAGS_FAIL = 'ADD_ASSETS_TAGS_FAIL';

export const GET_PEOPLE_TAGS_REQUEST = 'GET_PEOPLE_TAGS_REQUEST';
export const GET_PEOPLE_TAGS_SUCCESS = 'GET_PEOPLE_TAGS_SUCCESS';
export const GET_PEOPLE_TAGS_FAIL = 'GET_PEOPLE_TAGS_FAIL';

export const SEARCH_PEOPLE_FROM_FOOTER_REQUEST = 'SEARCH_PEOPLE_FROM_FOOTER_REQUEST';
export const SEARCH_PEOPLE_FROM_FOOTER_SUCCESS = 'SEARCH_PEOPLE_FROM_FOOTER_SUCCESS';
export const SEARCH_PEOPLE_FROM_FOOTER_FAIL = 'SEARCH_PEOPLE_FROM_FOOTER_FAIL';

export const CHANGE_VISIBILITY_MARKETPLACE_ASSET_REQUEST =
    'CHANGE_VISIBILITY_MARKETPLACE_ASSET_REQUEST';
export const CHANGE_VISIBILITY_MARKETPLACE_ASSET_SUCCESS =
    'CHANGE_VISIBILITY_MARKETPLACE_ASSET_SUCCESS';
export const CHANGE_VISIBILITY_MARKETPLACE_ASSET_FAIL = 'CHANGE_VISIBILITY_MARKETPLACE_ASSET_FAIL';

export const SET_VALUE_SEARCH_FROM_HOME_REQUEST = 'SET_VALUE_SEARCH_FROM_HOME_REQUEST';
export const SET_VALUE_SEARCH_FROM_HOME_SUCCESS = 'SET_VALUE_SEARCH_FROM_HOME_SUCCESS';
export const SET_VALUE_SEARCH_FROM_HOME_FAIL = 'SET_VALUE_SEARCH_FROM_HOME_FAIL';

export const SET_FILTER_BY_TAG_FROM_HOME = 'SET_FILTER_BY_TAG_FROM_HOME';

export const GET_FEATURED_ARTISTS_REQUETS = 'GET_FEATURED_ARTISTS_REQUETS';
export const GET_FEATURED_ARTISTS_SUCCESS = 'GET_FEATURED_ARTISTS_SUCCESS';
export const GET_FEATURED_ARTISTS_FAIL = 'GET_FEATURED_ARTISTS_FAIL';

export const FROM_FEATURED_ARTIST_REQUEST = 'FROM_FEATURED_ARTIST_REQUEST';
export const FROM_FEATURED_ARTIST_SUCCES = 'FROM_FEATURED_ARTIST_SUCCES';
export const FROM_FEATURED_ARTIST_FAIL = 'FROM_FEATURED_ARTIST_FAIL';

export const GET_MIN_CARD_PEOPLE_REQUEST = 'GET_MIN_CARD_PEOPLE_REQUEST';
export const GET_MIN_CARD_PEOPLE_SUCCESS = 'GET_MIN_CARD_PEOPLE_SUCCESS';
export const GET_MIN_CARD_PEOPLE_FAIL = 'GET_MIN_CARD_PEOPLE_FAIL';

export const GET_BANNER_PLACEHOLDER_REQUEST = 'GET_BANNER_PLACEHOLDER_REQUEST';
export const GET_BANNER_PLACEHOLDER_SUCCESS = 'GET_BANNER_PLACEHOLDER_SUCCESS';
export const GET_BANNER_PLACEHOLDER_FAIL = 'GET_BANNER_PLACEHOLDER_FAIL';

export const MARKETPLACE_PLACE_A_BID_SUCCESS = 'MARKETPLACE_PLACE_A_BID_SUCCESS';
export const MARKETPLACE_ASSET_BUY_NOW_SECCESS = 'MARKETPLACE_ASSET_BUY_NOW_SECCESS';
export const MAKE_OFFER_FROM_MARKETPLACE_SUCCESS = 'MAKE_OFFER_FROM_MARKETPLACE_SUCCESS';

export const CALL_ASSETS_ACTION_REQUEST = 'UPDATE_ASSET_VISIBILITIES_REQUEST';
export const CALL_ASSETS_ACTION_SUCCESS = 'UPDATE_ASSET_VISIBILITIES_SUCCESS';
export const CALL_ASSETS_ACTION_FAIL = 'UPDATE_ASSET_VISIBILITIES_FAIL';

export const REMOVE_ASSET_MARKETPLACE = 'REMOVE_ASSET_MARKETPLACE';
