export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';

export const GET_ALL_NOTIFICATIONS_REQUEST = 'GET_ALL_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_ALL_NOTIFICATIONS_SUCCESS';
export const GET_ALL_NOTIFICATIONS_FAIL = 'GET_ALL_NOTIFICATIONS_FAIL';

export const READ_NOTIFICATIONS_REQUEST = 'READ_NOTIFICATIONS_REQUEST';
export const READ_NOTIFICATIONS_SUCCESS = 'READ_NOTIFICATIONS_SUCCESS';
export const READ_NOTIFICATIONS_FAIL = 'READ_NOTIFICATIONS_FAIL';

export const LOAD_MORE_NOTIFICATIONS_REQUEST = 'LOAD_MORE_NOTIFICATIONS_REQUEST';
export const LOAD_MORE_NOTIFICATIONS_SUCCESS = 'LOAD_MORE_NOTIFICATIONS_SUCCESS';
export const LOAD_MORE_NOTIFICATIONS_FAIL = 'LOAD_MORE_NOTIFICATIONS_FAIL';

export const CLEAR_NOTIFICATIONS_SUCCESS = 'CLEAR_NOTIFICATIONS_SUCCESS';

export const SET_SOCKET_SUCCESS = 'SET_SOCKET_SUCCESS';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';
export const GET_UNREADED_NOTIFICATION_COUNT_SUCCESS = 'GET_UNREADED_NOTIFICATION_COUNT_SUCCESS';
export const ACTION_OFFER_NOTIFICATION = 'ACTION_OFFER_NOTIFICATION';
