export const GET_AUCTION_ASSETS_REQUEST = 'GET_AUCTION_ASSETS_REQUEST';
export const GET_AUCTION_ASSETS_SUCCESS = 'GET_AUCTION_ASSETS_SUCCESS';
export const GET_AUCTION_ASSETS_FAIL = 'GET_AUCTION_ASSETS_FAIL';

export const LOAD_MORE_AUCTION_ASSETS_REQUEST = 'LOAD_MORE_AUCTION_ASSETS_REQUEST';
export const LOAD_MORE_AUCTION_ASSETS_SUCCESS = 'LOAD_MORE_AUCTION_ASSETS_SUCCESS';
export const LOAD_MORE_AUCTION_ASSETS_FAIL = 'LOAD_MORE_AUCTION_ASSETS_FAIL';

export const PLACE_A_BID_SUCCESS = 'PLACE_A_BID_SUCCESS';
export const CLOSE_AUCTION_SUCCESS = 'CLOSE_AUCTION_SUCCESS';
