export const GET_TOP_BIDS_REQUEST = 'GET_TOP_BIDS_REQUEST';
export const GET_TOP_BIDS_SUCCESS = 'GET_TOP_BIDS_SUCCESS';
export const GET_TOP_BIDS_FAIL = 'GET_TOP_BIDS_FAIL';

export const FROM_TOP_BIDS = 'FROM_TOP_BIDS';
