export const GET_BEST_VOTED_REQUEST = 'GET_BEST_VOTED_REQUEST';
export const GET_BEST_VOTED_SUCCESS = 'GET_BEST_VOTED_SUCCESS';
export const GET_BEST_VOTED_FAIL = 'GET_BEST_VOTED_FAIL';

export const FROM_BEST_VOTED = 'FROM_BEST_VOTED';
