export const START_UPLOAD = 'START_UPLOAD';
export const FINISH_UPLOAD = 'FINISH_UPLOAD';

export const SEND_ASSETS_IDS_REQUEST = 'SEND_ASSETS_IDS_REQUEST';
export const SEND_ASSETS_IDS_SUCCESS = 'SEND_ASSETS_IDS_SUCCESS';
export const SEND_ASSETS_IDS_FAIL = 'SEND_ASSETS_IDS_FAIL';
