export const GET_SALES_HISTORY_REQUEST = 'GET_SALES_HISTORY_REQUEST';
export const GET_SALES_HISTORY_SUCCESS = 'GET_SALES_HISTORY_SUCCESS';
export const GET_SALES_HISTORY_FAIL = 'GET_SALES_HISTORY_FAIL';

export const LOAD_MORE_SALES_HISTORY_REQUEST = 'LOAD_MORE_SALES_HISTORY_REQUEST';
export const LOAD_MORE_SALES_HISTORY_SUCCESS = 'LOAD_MORE_SALES_HISTORY_SUCCESS';
export const LOAD_MORE_SALES_HISTORY_FAIL = 'LOAD_MORE_SALES_HISTORY_FAIL';
