export const GET_CREATED_ASSETS_REQUEST = 'GET_CREATED_ASSETS_REQUEST';
export const GET_CREATED_ASSETS_SUCCESS = 'GET_CREATED_ASSETS_SUCCESS';
export const GET_CREATED_ASSETS_FAIL = 'GET_CREATED_ASSETS_FAIL';

export const UPDATE_VISIBILITY_CREATED_ASSET_REQUEST = 'UPDATE_VISIBILITY_CREATED_ASSET_REQUEST';
export const UPDATE_VISIBILITY_CREATED_ASSET_SUCCESS = 'UPDATE_VISIBILITY_CREATED_ASSET_SUCCESS';
export const UPDATE_VISIBILITY_CREATED_ASSET_FAIL = 'UPDATE_VISIBILITY_CREATED_ASSET_FAIL';

export const LOAD_MORE_ASSETS_REQUEST = 'LOAD_MORE_ASSETS_REQUEST';
export const LOAD_MORE_ASSETS_SUCCESS = 'LOAD_MORE_ASSETS_SUCCESS';
export const LOAD_MORE_ASSETS_FAIL = 'LOAD_MORE_ASSETS_FAIL';

export const UPVOTING_CREATED_ASSET_SUCCESS = 'UPVOTING_CREATED_ASSET_SUCCESS';
export const UNUPVOTING_CREATED_ASSET_SUCCESS = 'UNUPVOTING_CREATED_ASSET_SUCCESS';
export const TO_FAVORITES_CREATED_SUCCESS = 'TO_FAVORITES_CREATED_SUCCESS';
export const REMOVE_FROM_FAVORITES_CREATED_SUCCESS = 'REMOVE_FROM_FAVORITES_CREATED_SUCCESS';
export const CLEAN_CREATED_ASSETS_SUCCESS = 'CLEAN_CREATED_ASSETS_SUCCESS';

export const CR_ASSET_PLACE_A_BID_SUCCESS = 'CR_ASSET_PLACE_A_BID_SUCCESS';
export const CR_ASSET_BUY_NOW_SECCESS = 'CR_ASSET_BUY_NOW_SECCESS';

export const MAKE_OFFER_FROM_CREATED_SUCCESS = 'MAKE_OFFER_FROM_CREATED_SUCCESS';

export const REMOVE_ASSET_CREATED = 'REMOVE_ASSET_CREATED';
